blank_issues_enabled: true
contact_links:
  - name: 💬 質問・相談
    url: https://github.com/upbond/festaria/discussions
    about: 開発に関する質問や相談はDiscussionsをご利用ください
  - name: 📖 ドキュメント
    url: https://github.com/upbond/festaria/tree/main/docs
    about: プロジェクトのドキュメントはこちらをご確認ください